### PR TITLE
add theme settings (dark / light mode and custom color)

### PR DESCRIPTION
**Pull request by exane**
Hey Shadyabhi,

i've been using your awesome highlighter for quite some time now and recently changed my reddit to dark mode. Sadly I couldn't find any options to match the color scheme, so I've added them by myself.

There're now 3 additional settings in the options menu: 
- Checkbox to switch between light and dark mode
- Custom color scheme for light and dark mode

The default keeps the same as before: light mode with FFFDCC as color.

### CODE REVIEW

**Comment by shadyabhi** [comment]
Hi @exane , thanks for the awesome PR. I'm going to check everything tonight and publish it.

Thanks

**Comment by Primeey** [comment]
Sorry for bringing up such a old thread but why did this not get implemented? It's a very good feature. Just look at this [example](http://i.imgur.com/tP4w1A1.png) the comment is not readable because of the subreddits theme + this extension clashing

**Comment by shadyabhi** [comment]
Hi @Primeey, let me test this in next few days and publish. I'll update it here.

**Comment by shadyabhi** [comment]
Sorry for the delay.

**Comment by shadyabhi** [comment]
Thanks for the fix @exane and sorry for the delay. Updating the chrome extension in the next few minutes.

**Pull request merged**
